"""Added is_active to PettyCash

Revision ID: 7d8002a8f226
Revises: 9c5ec2415f5c
Create Date: 2026-06-06 10:11:50.038111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d8002a8f226'
down_revision = '9c5ec2415f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
