"""Added petty cash models with fixes

Revision ID: 9c5ec2415f5c
Revises: 1cafbf1e067d
Create Date: 2026-06-06 10:05:45.247241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c5ec2415f5c'
down_revision = '1cafbf1e067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petty_cash_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('ledger_type', sa.Enum('Direct', 'Indirect'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('uq_ledger_name_lower', 'petty_cash_ledger', [sa.text('LOWER(ledger_name)')], unique=True)
    op.create_table('petty_cash',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('voucher_name', sa.String(length=255), nullable=False),
    sa.Column('voucher_type', sa.Enum('Payment', 'Received'), nullable=False),
    sa.Column('ledger_id', sa.BigInteger(), nullable=False),
    sa.Column('paid_to', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('Cash', 'UPI'), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['petty_cash_ledger.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.create_index('idx_petty_cash_branch_year', ['branch_id', 'academic_year'], unique=False)
        batch_op.create_index('idx_petty_cash_date', ['transaction_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.drop_index('idx_petty_cash_date')
        batch_op.drop_index('idx_petty_cash_branch_year')

    op.drop_table('petty_cash')
    op.drop_table('petty_cash_ledger')
    # ### end Alembic commands ###
