"""Added description and approved_by to PettyCash

Revision ID: ac218858f25b
Revises: 7d8002a8f226
Create Date: 2026-06-06 10:22:52.305933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac218858f25b'
down_revision = '7d8002a8f226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash', schema=None) as batch_op:
        batch_op.drop_column('approved_by')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
