"""add attempts

Revision ID: b0a4f124c7e1
Revises: cc2a2a5a3644
Create Date: 2026-03-11 14:55:36.517801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a4f124c7e1'
down_revision = 'cc2a2a5a3644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_otps', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
